########################################################################
#  SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0-only)
#  Copyright(c) 2016, 2021 Intel Corporation
########################################################################
ccflags-y := -I$(src)/../qat_common
obj-$(CONFIG_CRYPTO_DEV_QAT_D15XXVF) += qat_d15xxvf.o
qat_d15xxvf-objs := adf_drv.o adf_d15xxvf_hw_data.o
