########################################################################
#  SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0-only)
#  Copyright(c) 2016, 2021 Intel Corporation
########################################################################
ccflags-y := -I$(src)/../qat_common
obj-$(CONFIG_CRYPTO_DEV_QAT_D15XX) += qat_d15xx.o
qat_d15xx-objs := adf_drv.o adf_d15xx_hw_data.o
