########################################################################
#  SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0-only)
#  Copyright(c) 2020 - 2021 Intel Corporation
########################################################################
ccflags-y := -I$(src)/../qat_common
obj-$(CONFIG_CRYPTO_DEV_QAT_200XXVF) += qat_200xxvf.o
qat_200xxvf-objs := adf_drv.o adf_200xxvf_hw_data.o
