########################################################################
#  SPDX-License-Identifier: (BSD-3-Clause OR GPL-2.0-only)
#  Copyright(c) 2020 - 2021 Intel Corporation
########################################################################
ccflags-y := -I$(src)/../qat_common
obj-$(CONFIG_CRYPTO_DEV_QAT_200XX) += qat_200xx.o
qat_200xx-objs := adf_drv.o adf_200xx_hw_data.o
